### ISSUE TITLE
Address type detection + validation

### ISSUE THREAD

**Issue by Klakurka** [PayButton/paybutton-server#145]
Related: https://github.com/PayButton/paybutton-server/pull/144#issuecomment-1169353622

The Cashtab team is working on a new lib to replace `xec-js` which might work for us but still TBD.

Basically if somebody omits the prefix when entering an address (eg. adding a button), we need to find out if it's an XEC or BCH address (which can be done easily using a lib).

**Comment by chedieck** [comment]
Upon investigating this issue, I found that `bch-js`, which implements both eCash and Bitcoin Cash address validation, does so by sending a request to `abc.fullstack.cash` or `bchn.fullstack.cash`, respectivelly (e.g: https://abc.fullstack.cash/v5/util/validateAddress/qpxy9ur3asntwffm9a6pdpyhdrkyrdha3qmepdpa4t will tell us the address is invalid and https://bchn.fullstack.cash/v5/util/validateAddress/qpxy9ur3asntwffm9a6pdpyhdrkyrdha3qmepdpa4t will tell us it is valid, so its valid for bch only).
- ([validateAddress method implementation on bch-js](https://github.com/Permissionless-Software-Foundation/bch-js/blob/37fe6798003dc08a58577a6cef86b962c6945067/src/util.js#L272))

Those URLs, in turn, seems to running  `bch-api`, which also validates the addresses by sending a request to some bch / ecash node (I supposed this request is authenticated).

- ([validateAddressSingle method implementation on bch-api](https://github.com/Permissionless-Software-Foundation/bch-api/blob/df27ba20634fa1ac68c02747062d575d65666620/src/routes/v5/util.js#L63))


1. We could, therefore, use those libs or even implement it the same way: just do the request and use the response to decide if a address is valid or not, or to infer the chain to which the address belongs, etc. I don't like this idea very much because it means we rely on a third-party to be up & working (just to do some computation) and also it's slow: having to send those requests and wait for the responses every time we want to validate some address.

2. Another option is to use another library: I have found two, [bchaddrjs](https://github.com/ealmansi/bchaddrjs) and [ecashaddrjs](https://github.com/bytesofman/ecashaddrjs), that appear to implement the actual computation of this validation. The first one does it only for BCH, while the second does it both for BCH and eCash, but seems to be less known. So we wouldn't have to use both of them, but we would have to use the second one, therefore this solution has the drawback of having to rely on a small lib.

3. Finally, we could implement it ourselves. And even though I would find very interesting to do that myself, I don't think we should go this way: first because of the obvious time-consuming aspect of choosing this solution, second because this problem seems to me like a separate problem of its own; so embedding its solution among the rest of the paybutton-server code looks like a violation of the "do one thing and do it well" principle.


My preferred solution is 2; please let me know what you guys think.

**Comment by Klakurka** [comment]
Oh yeah ok that's the lib - Joey made it in a pinch.

Ya 100% let's go with option 2.
