### ISSUE TITLE
Process for keeping currency values up to date (and retained for each day)

### ISSUE THREAD

**Issue by Klakurka** [PayButton/paybutton-server#223]
Related to #63 and #105.

Basically the only requirements for this are:

- We have a price for every day that we have a transaction for (for each currency); not necessarily a price for every day ever.
- We have a recent (maybe updated every 5-15 minutes) price for each currency. "What's the price now?"

**Comment by chedieck** [comment]
My idea to implement this, so far:
-  Create `Price` table with columns: id, quote, date, value & chainId. (quote will only be USD for now, later we can add e.g. BTC)
-  Script to populate the `Price` table using the `Transaction` timestamps.

The `date` field could be simply a YYYY-MM-DD string, since we want only one `Price` for each day.

Another option is to have one `Price` for each timestamp (and thus have a `timestamp` column instead of `date`), which will increase the time needed to fetch & save all prices, but give us more accurate information.

**Comment by Klakurka** [comment]
Having a price for each time stamp actually does sound better but if we did that then in reality we'd have a mix of "accurate" prices and "daily" prices on use because most txs we'd probably not actually see in the system until they log in later.

**Comment by Klakurka** [comment]
It's simpler to just go with a daily price though.

**Comment by chedieck** [comment]
> Having a price for each time stamp actually does sound better but if we did that then in reality we'd have a mix of "accurate" prices and "daily" prices on use because most txs we'd probably not actually see in the system until they log in later.

I am not sure if I understand; but I think we could have `Price`s with a `timestamp` field for the timestamps relevant to the `Transaction`s; and on top of that `Price`s with `timestamp == 0` representing the current price (updated every N minutes).

**Comment by chedieck** [comment]
Solved with #300
